apiVersion: v2
name: nfs-subdir-external-provisioner
version: 0.0.1
dependencies:
- name: nfs-subdir-external-provisioner
  version: 4.0.15
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
