minio:
  defaultBucket:
    enabled: true
    name: argo-artifacts
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  existingSecret: argo-workflows-minio
  ingress:
    enabled: true
    hosts:
    - minio.tanzu.blah.cloud
  resources:
    requests:
      memory: 2Gi
  securityContext:
    enabled: false