kibana:
  ingress:
    enabled: true
    hosts:
      - host: kibana.tanzu.blah.cloud
        paths:
        - path: /
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-live
    tls:
    - secretName: kibana-cert
      hosts:
        - kibana.tanzu.blah.cloud
  # resources:
  #   requests:
  #     cpu: null
  #   limits:
  #     cpu: null
  elasticsearchHosts: "https://es.tanzu.blah.cloud"